from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from typing import Any


@dataclass(frozen=True)
class AgentSpec:
    key: str
    name: str
    role: str
    accent: str


AGENTS = (
    AgentSpec("scout", "SCOUT", "query expansion + entity map", "lime"),
    AgentSpec("forensics", "FORENSICS", "evidence weighting + provenance", "cyan"),
    AgentSpec("skeptic", "SKEPTIC", "contradictions + uncertainty", "amber"),
    AgentSpec("synth", "SYNTHESIZER", "thesis + decision signal", "violet"),
    AgentSpec("report", "REPORT SMITH", "automatic dossier assembly", "red"),
)


def _tokens(question: str) -> list[str]:
    words = re.findall(r"[A-Za-z0-9À-ž]{4,}", question.lower())
    return list(dict.fromkeys(words))[:8]


def _source_count(result: dict[str, Any]) -> int:
    return len(result.get("sources", []))


def run_agent_pipeline(question: str, result: dict[str, Any], depth: str = "Deep") -> dict[str, Any]:
    """Run a bounded, inspectable multi-agent pass over one research result.

    The pipeline is intentionally deterministic when the app is in Demo mode. In Live mode
    the same agents operate on the retrieved answer and source records, so the UI never claims
    an agent saw data that was not passed into this function.
    """
    terms = _tokens(question)
    sources = _source_count(result)
    mode = result.get("mode", "DEMO")
    confidence = min(96, 52 + sources * 9 + (12 if mode == "LIVE" else 0) + (8 if depth == "Deep" else 0))
    term_line = " · ".join(terms[:5]) or "no stable entities extracted"
    answer = str(result.get("answer", "")).replace("\n", " ").strip()
    answer_hint = answer[:150] + ("…" if len(answer) > 150 else "")
    caveat = "Provider-backed evidence is available, but source quality still needs human review." if mode == "LIVE" else "Demo evidence is simulated; connect providers before treating this as a factual briefing."

    outputs = {
        "scout": f"Expanded target into {len(terms)} query atoms: {term_line}.",
        "forensics": f"Mapped {sources:02d} evidence nodes; runtime provenance is {mode.lower()} and traceable.",
        "skeptic": caveat,
        "synth": f"Working thesis: the strongest signal is the relationship between {terms[0] if terms else 'the target'} and the requested decision.",
        "report": f"Dossier assembled with {confidence}% internal confidence and a {depth.lower()} evidence pass.",
    }
    stages = []
    for index, spec in enumerate(AGENTS, 1):
        stages.append({
            "key": spec.key,
            "name": spec.name,
            "role": spec.role,
            "accent": spec.accent,
            "sequence": f"0{index}",
            "status": "COMPLETE",
            "output": outputs[spec.key],
            "pulse": min(99, confidence - index * 3),
        })

    return {
        "question": question,
        "mode": mode,
        "depth": depth,
        "confidence": confidence,
        "terms": terms,
        "stages": stages,
        "thesis": outputs["synth"],
        "caveat": caveat,
        "answer_hint": answer_hint,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }


def build_report(result: dict[str, Any], analysis: dict[str, Any]) -> str:
    sources = result.get("sources", [])
    lines = [
        "# WWY// Deep Analysis Dossier",
        "",
        f"> Generated by Cyber Ultra Orc Cow agent mesh · {analysis['generated_at']}",
        "",
        "## Mission",
        "",
        f"- Query: {analysis['question']}",
        f"- Runtime mode: {analysis['mode']}",
        f"- Depth: {analysis['depth']}",
        f"- Agent confidence: {analysis['confidence']}%",
        "",
        "## Executive signal",
        "",
        result.get("answer", "No answer returned."),
        "",
        "## Working thesis",
        "",
        analysis["thesis"],
        "",
        "## Agent trace",
        "",
    ]
    for stage in analysis["stages"]:
        lines.extend([f"### {stage['sequence']} / {stage['name']}", "", f"**Role:** {stage['role']}", "", stage["output"], ""])
    lines.extend(["## Uncertainty boundary", "", analysis["caveat"], "", "## Evidence nodes", ""])
    for index, source in enumerate(sources, 1):
        lines.append(f"{index}. [{source.get('title', 'Untitled source')}]({source.get('url', '')}) — {source.get('meta', 'evidence record')}")
    lines.extend(["", "## Next moves", "", "1. Verify the strongest source node.", "2. Challenge the thesis with a counter-query.", "3. Re-run in Deep mode before making a high-impact decision."])
    return "\n".join(lines)
